# Generated by Django 5.1.2 on 2024-10-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='benefits',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Социальные пособия'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='children',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество детей'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Семейное положение'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион'),
        ),
    ]
