# Generated by Django 5.1.1 on 2024-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_telegramuser_total_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='quiz_points',
            field=models.IntegerField(default=0, verbose_name='Очки за квиз'),
        ),
    ]
